"""added table request_product

Revision ID: 4c678e8f5275
Revises: 980c76e370bb
Create Date: 2024-10-16 16:39:23.188350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c678e8f5275'
down_revision: Union[str, None] = '980c76e370bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('products', sa.ARRAY(sa.Integer(), dimensions=1), nullable=False),
    sa.Column('positions', sa.ARRAY(sa.Integer(), dimensions=1), nullable=False),
    sa.Column('natural_positions', sa.ARRAY(sa.Integer(), dimensions=1), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_product')
    # ### end Alembic commands ###
