"""added index on request_product.products

Revision ID: 9414672ee87c
Revises: c226e3e633d2
Create Date: 2024-10-23 03:48:09.119559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9414672ee87c'
down_revision: Union[str, None] = 'c226e3e633d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_request_product_products', 'request_product', ['products'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_request_product_products', table_name='request_product', postgresql_using='gin')
    # ### end Alembic commands ###
