services:
  db:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./app_data/db:/var/lib/clickhouse

  searcher:
    build:
      dockerfile: Dockerfile
    container_name: wb_searcher
    env_file:
      - .env
    volumes:
      - ./logs:/app_data/logs/searcher
    ports:
      - "9013:9013"
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:alpine

  celery:
    build: .
    entrypoint: celery -A tasks.celery_app worker --loglevel=info
    volumes:
      - ./logs:/app_data/logs/celery
    depends_on:
      - redis

  celery-beat:
    build: .
    entrypoint: celery -A tasks.celery_app beat --loglevel=info
    volumes:
      - ./logs:/app_data/logs/celery_beat
    depends_on:
        - redis


networks:
  wb_search:
